# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"S3": "s3bz.ipynb",
         "generalSave": "s3bz.ipynb",
         "generalLoad": "s3bz.ipynb",
         "saveZl": "s3bz.ipynb",
         "loadZl": "s3bz.ipynb",
         "savePklZl": "s3bz.ipynb",
         "loadPklZl": "s3bz.ipynb",
         "Requests": "s3bz.ipynb"}

modules = ["s3bz.py"]

doc_url = "https://fastai.github.io/s3bz/"

git_url = "https://github.com/fastai/s3bz/tree/master/"

def custom_doc_links(name): return None
